/**
 * Evidence-led pilot v2 — M01–M26 implementation ledger (Unit 0).
 *
 * GENERATED by scripts/pilot/derive-evidence-ledger.py from the frozen
 * decision workbook (sheet 09_M01_M26_FINAL). Do not edit by hand.
 *
 * PURE module (no Phaser, no import.meta): Node-importable for pure tests.
 * The exact source item wording is deliberately ABSENT from this module so
 * no questionnaire text ever enters the game bundle; it lives only in
 * docs/verification/evidence-led-pilot-v2/M01-M26-IMPLEMENTATION-LEDGER.json
 * for criterion comparison.
 *
 * Scientific boundary: dispositions, constructs, raw components and validity
 * gates are copied verbatim from the workbook and are FROZEN. Every route
 * identifier is provisional (`proto_*` / `secondary_*`) — never a canonical
 * event name; nothing here is a score, weight, formula, trait label or cut
 * score; missing/invalid opportunities never become low values.
 */

export type LedgerItemId =
  | 'M01'
  | 'M02'
  | 'M03'
  | 'M04'
  | 'M05'
  | 'M06'
  | 'M07'
  | 'M08'
  | 'M09'
  | 'M10'
  | 'M11'
  | 'M12'
  | 'M13'
  | 'M14'
  | 'M15'
  | 'M16'
  | 'M17'
  | 'M18'
  | 'M19'
  | 'M20'
  | 'M21'
  | 'M22'
  | 'M23'
  | 'M24'
  | 'M25'
  | 'M26';

export type LedgerDispositionClass =
  | 'strong'
  | 'conditional'
  | 'questionnaire_primary';

export type LedgerEpisode = 1 | 2 | 3 | 4 | 5 | 6;

export interface LedgerWindow {
  /** Provisional window/version id (item-owned). */
  id: string;
  episode: LedgerEpisode;
  /** Occasion tag for repeated-occasion items; null otherwise. */
  occasion: string | null;
}

export interface LedgerRoute {
  location: string;
  mechanic: string;
  episodes: LedgerEpisode[];
  /** Provisional SA-13 opportunity ids (empty for questionnaire-primary items). */
  opportunity_ids: string[];
  windows: LedgerWindow[];
  /** Primary event-family prefixes; pairwise disjoint across items. */
  family_prefixes: string[];
  /** Secondary contextual telemetry ids (never primary evidence). */
  secondary_telemetry_ids: string[];
  implementation_status: 'planned' | 'implemented' | 'partial';
}

export interface EvidenceLedgerEntry {
  id: LedgerItemId;
  instrument: string;
  facet_or_scale: string;
  /** Verbatim sheet 09 disposition. */
  final_disposition: string;
  disposition_class: LedgerDispositionClass;
  analysis_level: string;
  final_game_opportunity: string;
  /** Raw components only — never a score. */
  candidate_raw_variables: string[];
  validity_gate: string;
  rival_explanations: string;
  active_seconds: number;
  implementation_action: string;
  episode_label: string;
  primary_source: string;
  route: LedgerRoute;
}

export const LEDGER_WORKBOOK_MD5 = '1535682ab88481815bbdda1206644d4c';
export const LEDGER_SHEET = '09_M01_M26_FINAL';

export const LEDGER_EPISODES: Record<LedgerEpisode, string> = {
  1: 'Storm Arrival & Incident Handover',
  2: 'Records & Workshop Restoration',
  3: 'Signal Analysis Incident',
  4: 'Exterior Recovery',
  5: 'Return, Revision & Handover',
  6: 'Utility & Core Closure',
};

export const LEDGER_INFERENCE_MODEL: readonly {
  instrument: string;
  facet_or_scale: string;
  items: LedgerItemId[];
}[] = [
  {
    instrument: 'BFI-2',
    facet_or_scale: 'Organization',
    items: ['M01', 'M02', 'M03', 'M04'],
  },
  {
    instrument: 'BFI-2',
    facet_or_scale: 'Productiveness',
    items: ['M05', 'M06', 'M07', 'M08'],
  },
  {
    instrument: 'BFI-2',
    facet_or_scale: 'Responsibility',
    items: ['M09', 'M10', 'M11', 'M12'],
  },
  {
    instrument: 'BESSI-192',
    facet_or_scale: 'Information Processing Skill',
    items: ['M13', 'M14', 'M15', 'M16', 'M17', 'M18'],
  },
  {
    instrument: 'Multidimensional Persistence Scale',
    facet_or_scale: 'Persistence Despite Difficulty',
    items: ['M19', 'M20', 'M21', 'M22', 'M23'],
  },
  {
    instrument: 'Multidimensional Persistence Scale',
    facet_or_scale: 'Inappropriate Persistence',
    items: ['M24', 'M25', 'M26'],
  },
];

export const LEDGER_BURDEN_BUDGET = {
  item_owned_active_seconds: 1040,
  shared_overhead_seconds: 420,
  non_scored_closure_seconds: 75,
  planned_total_seconds: 1535,
  human_median_target_minutes: 27,
  human_p90_gate_minutes: 30,
  status: 'Planning estimate only — requires human pilot',
} as const;

export const EVIDENCE_LEDGER: readonly EvidenceLedgerEntry[] = [
  {
    id: 'M01',
    instrument: 'BFI-2 Conscientiousness',
    facet_or_scale: 'Organization',
    final_disposition: 'GAME-CANDIDATE — CONDITIONAL',
    disposition_class: 'conditional',
    analysis_level: 'Organization facet first; item component exploratory',
    final_game_opportunity:
      'Storm incident board: inspect a compact packet, create a dependency-valid work order, then execute the first three transitions. Permit at least two equally valid orders.',
    candidate_raw_variables: [
      'order_board_state',
      'dependency_violations',
      'precommit_corrections',
      'first_three_transitions',
    ],
    validity_gate:
      'Briefing comprehension passed; every document visible; no time pressure; matched form; board actions isolated from M05/M12/M14.',
    rival_explanations:
      'Reading/planning ability; interface literacy; overly explicit instructions suppress trait expression.',
    active_seconds: 35,
    implementation_action:
      "REVISE current board; do not score one 'correct' sequence.",
    episode_label: '1 Incident Handover',
    primary_source: 'https://doi.org/10.1037/pspp0000096',
    route: {
      location: 'Station Concourse / Incident Desk - plan board',
      mechanic:
        'Storm incident plan board: inspect a compact packet, order the work into a dependency-valid sequence (two or more valid orders), then execute the first three transitions.',
      episodes: [1],
      opportunity_ids: ['proto_m01_plan_board'],
      windows: [{ id: 'm01_plan_board_w1', episode: 1, occasion: null }],
      family_prefixes: ['proto_m01_board_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M02',
    instrument: 'BFI-2 Conscientiousness',
    facet_or_scale: 'Organization',
    final_disposition: 'GAME-CANDIDATE — CONDITIONAL',
    disposition_class: 'conditional',
    analysis_level:
      'Organization facet first; reverse-keyed component exploratory',
    final_game_opportunity:
      'Open workspace: manage six cases with optional folders/labels, then retrieve two counterbalanced cases before committing the handover.',
    candidate_raw_variables: [
      'case_location_at_close',
      'untraceable_case_count',
      'misfile_count',
      'duplicate_count',
      'retrieval_actions',
      'retrieval_errors',
    ],
    validity_gate:
      'Identical cases; multiple valid organization schemas; retrieval probes fixed by form; no inventory carryover; full keyboard/pointer equivalence.',
    rival_explanations:
      'Working memory; categorization; UI mastery. Correct-bin sorting alone is not sufficient evidence.',
    active_seconds: 35,
    implementation_action:
      'REPLACE filing-as-answer-key with functional traceability + retrieval.',
    episode_label: '2 Records & Workshop',
    primary_source: 'https://doi.org/10.1037/pspp0000096',
    route: {
      location: 'Records Workshop - open case workspace',
      mechanic:
        'Open workspace: six heterogeneous case bundles, optional folders and labels, free placement; then retrieval of two counterbalanced cases before the handover commit. No designer-preferred layout is scored.',
      episodes: [2],
      opportunity_ids: ['proto_m02_case_workspace'],
      windows: [
        { id: 'm02_workspace_w1', episode: 2, occasion: null },
        { id: 'm02_retrieval_w1', episode: 2, occasion: null },
      ],
      family_prefixes: ['proto_m02_case_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M03',
    instrument: 'BFI-2 Conscientiousness',
    facet_or_scale: 'Organization',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level: 'Organization facet; aggregate two item-owned occasions',
    final_game_opportunity:
      'After two unrelated jobs, allow an optional workstation reset: return the same number of item-local tools/materials to clearly marked homes before leaving.',
    candidate_raw_variables: [
      'objects_restored_o1',
      'homes_correct_o1',
      'close_state_o1',
      'objects_restored_o2',
      'homes_correct_o2',
      'close_state_o2',
    ],
    validity_gate:
      'Matched object counts; independent spawn; exit remains open; no explicit cleanup order; M04 debris excluded.',
    rival_explanations:
      'Demand characteristics; cue salience; matching ability.',
    active_seconds: 25,
    implementation_action:
      'KEEP inventory foundation; add two natural route occasions.',
    episode_label: '2 + 5',
    primary_source: 'https://doi.org/10.1037/pspp0000096',
    route: {
      location:
        'Records Workshop press (occasion 1) and Workshop Return press (occasion 2)',
      mechanic:
        'After an unrelated job the workstation is left with a fixed number of item-local residuals and clearly marked homes; the reset is optional and never instructed; exit stays open.',
      episodes: [2, 5],
      opportunity_ids: ['proto_m03_reset_a', 'proto_m03_reset_b'],
      windows: [
        { id: 'm03_reset_o1', episode: 2, occasion: 'a' },
        { id: 'm03_reset_o2', episode: 5, occasion: 'b' },
      ],
      family_prefixes: ['proto_m03_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M04',
    instrument: 'BFI-2 Conscientiousness',
    facet_or_scale: 'Organization',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level: 'Organization facet; reverse-keyed item component',
    final_game_opportunity:
      'A neutral sample job creates six standardized, self-generated debris objects. Disposal is optional and the route never gates on cleanup.',
    candidate_raw_variables: [
      'debris_remaining_at_exit',
      'debris_disposed',
      'cleanup_latency',
      'window_exposure',
    ],
    validity_gate:
      'Exactly six salient/reachable objects; disposal works; no time pressure; debris not reused by M03; route exit always available.',
    rival_explanations: 'Perceived norms; salience; demand characteristics.',
    active_seconds: 25,
    implementation_action:
      'KEEP, but visually strengthen debris and test untouched/partial/full states.',
    episode_label: '2 Records & Workshop',
    primary_source: 'https://doi.org/10.1037/pspp0000096',
    route: {
      location: 'Records Workshop - sample-job debris',
      mechanic:
        'A neutral sample job creates six standardised, self-generated debris objects; disposal is optional, the route never gates on cleanup, debris is never reused by M03.',
      episodes: [2],
      opportunity_ids: ['proto_m04_debris_cleanup'],
      windows: [{ id: 'm04_debris_w1', episode: 2, occasion: null }],
      family_prefixes: ['proto_m04_debris_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M05',
    instrument: 'BFI-2 Conscientiousness',
    facet_or_scale: 'Productiveness',
    final_disposition: 'GAME-CANDIDATE — CONDITIONAL',
    disposition_class: 'conditional',
    analysis_level: 'Productiveness facet; aggregate two micro-opportunities',
    final_game_opportunity:
      'After objective comprehension, present two low-risk visible faults at separate quiet moments without an NPC command; other actions remain neutral.',
    candidate_raw_variables: [
      'eligible_opportunity',
      'initiation_latency',
      'initiated',
      'censored_reason',
      'occasion_id',
    ],
    validity_gate:
      'Clock starts after comprehension; fixed distance/access; valid focus/input state; no competing mandatory action; latency censoring preserved.',
    rival_explanations:
      'Caution; uncertainty; motor speed; one situation is too narrow.',
    active_seconds: 20,
    implementation_action:
      'REVISE from one latency to two matched, comprehension-gated occasions.',
    episode_label: '1 + 4',
    primary_source: 'https://doi.org/10.1037/pspp0000096',
    route: {
      location:
        'Concourse visible fault (occasion 1); Recovery Yard visible fault (occasion 2)',
      mechanic:
        'Two low-risk visible faults at separate quiet moments after objective comprehension, without an NPC command; the initiation clock starts after comprehension and latency censoring is preserved.',
      episodes: [1, 4],
      opportunity_ids: ['proto_m05_initiation_o1', 'proto_m05_initiation_o2'],
      windows: [
        { id: 'm05_initiation_o1', episode: 1, occasion: 'o1' },
        { id: 'm05_initiation_o2', episode: 4, occasion: 'o2' },
      ],
      family_prefixes: ['proto_m05_initiation_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M06',
    instrument: 'BFI-2 Conscientiousness',
    facet_or_scale: 'Productiveness',
    final_disposition: 'GAME-CANDIDATE — CONDITIONAL',
    disposition_class: 'conditional',
    analysis_level:
      'Productiveness facet; quality-adjusted work-sample component',
    final_game_opportunity:
      'After non-scored practice, compose and dispatch four routine pseudo-commands using visible tokens/reference; typing is optional, not required.',
    candidate_raw_variables: [
      'correct_dispatches',
      'invalid_commands',
      'excess_actions',
      'active_time_excl_animation',
      'practice_passed',
    ],
    validity_gate:
      'Practice criterion; matched commands; quality floor; animation excluded; keyboard/pointer semantic equivalence.',
    rival_explanations:
      'Working memory; interface fluency; gaming experience. Speed alone is prohibited.',
    active_seconds: 35,
    implementation_action:
      'KEEP engine; simplify presentation and pre-register only raw components.',
    episode_label: '2 Records & Workshop',
    primary_source: 'https://doi.org/10.1037/pspp0000096',
    route: {
      location: 'Records Workshop - dispatch console',
      mechanic:
        'After non-scored practice, compose and dispatch four routine pseudo-commands from visible tokens/reference; typing optional; animation time excluded.',
      episodes: [2],
      opportunity_ids: ['proto_m06_routine_dispatch'],
      windows: [{ id: 'm06_dispatch_w1', episode: 2, occasion: null }],
      family_prefixes: ['proto_m06_dispatch_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M07',
    instrument: 'BFI-2 Conscientiousness',
    facet_or_scale: 'Productiveness',
    final_disposition: 'GAME-CANDIDATE — CONDITIONAL',
    disposition_class: 'conditional',
    analysis_level:
      'Productiveness facet; distinguish routine finish-through from PDD',
    final_game_opportunity:
      'Six-stage routine calibration with visible endpoint and persistent state; participant may leave and naturally return. No injected setback or difficulty spike.',
    candidate_raw_variables: [
      'stages_completed',
      'voluntary_returns',
      'useful_reengagement',
      'completion',
      'departure_state',
    ],
    validity_gate:
      'Attainable; controls known; endpoint visible; no setback; state persists; no route gate forcing completion.',
    rival_explanations: 'Interest; ability; fatigue; completion pressure.',
    active_seconds: 35,
    implementation_action:
      'IMPLEMENT as routine project, not the difficult persistence task.',
    episode_label: '2 + 5',
    primary_source: 'https://doi.org/10.1037/pspp0000096',
    route: {
      location:
        'Records Workshop calibration bench (start) / Workshop Return (end)',
      mechanic:
        'Six-stage routine calibration with a visible endpoint and persistent state; the participant may leave and naturally return; no injected setback or difficulty spike; no route gate forces completion.',
      episodes: [2, 5],
      opportunity_ids: ['proto_m07_calibration_project'],
      windows: [
        { id: 'm07_calibration_start', episode: 2, occasion: null },
        { id: 'm07_calibration_end', episode: 5, occasion: null },
      ],
      family_prefixes: ['proto_m07_calibration_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M08',
    instrument: 'BFI-2 Conscientiousness',
    facet_or_scale: 'Productiveness',
    final_disposition: 'QUESTIONNAIRE-PRIMARY',
    disposition_class: 'questionnaire_primary',
    analysis_level:
      'Exact BFI-2 item; optional work behavior is secondary only',
    final_game_opportunity:
      'No scored standalone minigame. Two naturally available useful jobs may generate descriptive secondary telemetry only.',
    candidate_raw_variables: [
      'secondary_optional_job_engagement',
      'eligible_context',
      'fatigue_context',
    ],
    validity_gate:
      'Never interpreted as a score; exact item remains in questionnaire; no rewards/route gates tied to engagement.',
    rival_explanations:
      'Moralized/broad wording; fatigue; boredom; reward preference; task meaning.',
    active_seconds: 0,
    implementation_action:
      'REMOVE primary game inference; retain exact questionnaire item.',
    episode_label: 'Across route — secondary only',
    primary_source: 'https://doi.org/10.1037/pspp0000096',
    route: {
      location: 'Across route - two naturally available optional useful jobs',
      mechanic:
        'No scored minigame. Optional-job engagement is descriptive secondary telemetry only and is never interpreted as a score; the exact item stays in the questionnaire.',
      episodes: [],
      opportunity_ids: [],
      windows: [],
      family_prefixes: [],
      secondary_telemetry_ids: ['secondary_m08_optional_job'],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M09',
    instrument: 'BFI-2 Conscientiousness',
    facet_or_scale: 'Responsibility',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level:
      'Responsibility facet; aggregate two scheduled item-owned checks',
    final_game_opportunity:
      'Voluntarily accept a monitor watch with two scheduled gauge checks at fixed route milestones, equal reminders and guaranteed access.',
    candidate_raw_variables: [
      'check1_completed',
      'check2_completed',
      'due_delta_1',
      'due_delta_2',
      'reminder_exposure',
    ],
    validity_gate:
      'Explicit acceptance; both windows presented; no competing mandatory task; route access identical; failures distinguished from invalid presentation.',
    rival_explanations:
      'Prospective memory; route knowledge; interruption exposure.',
    active_seconds: 25,
    implementation_action:
      'KEEP and intentionally require one meaningful return through the hub.',
    episode_label: '1 + 5',
    primary_source: 'https://doi.org/10.1037/pspp0000096',
    route: {
      location:
        'Concourse monitor gauge - accepted in episode 1; check 1 due before leaving the Concourse, check 2 due on the return',
      mechanic:
        'Voluntarily accept a monitor watch with two scheduled gauge checks at fixed milestones, equal reminders and guaranteed access; failures are distinguished from invalid presentation.',
      episodes: [1, 5],
      opportunity_ids: ['proto_m09_monitor_watch'],
      windows: [
        { id: 'm09_check_1', episode: 1, occasion: 'check1' },
        { id: 'm09_check_2', episode: 5, occasion: 'check2' },
      ],
      family_prefixes: ['proto_m09_watch_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M10',
    instrument: 'BFI-2 Conscientiousness',
    facet_or_scale: 'Responsibility',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level: 'Responsibility facet; bounded social commitment',
    final_game_opportunity:
      'Voluntarily accept delivery of a named component, receive a standardized interruption, and later hand it to the available named NPC.',
    candidate_raw_variables: [
      'promise_accepted',
      'promise_fulfilled',
      'handover_delay',
      'interruption_exposure',
      'cutoff_state',
    ],
    validity_gate:
      'Explicit acceptance; item/recipient always available; one neutral reminder; no dialogue wording scored.',
    rival_explanations: 'Memory; navigation; social desirability.',
    active_seconds: 20,
    implementation_action:
      'KEEP; use Vale/Kai/Noor with persistent mission log and natural return.',
    episode_label: '1 + 5',
    primary_source: 'https://doi.org/10.1037/pspp0000096',
    route: {
      location: 'Concourse (accept) -> named NPC on the return (handover)',
      mechanic:
        'Voluntarily accept delivery of a named component, receive a standardised interruption, and later hand it to the available named NPC; one neutral reminder; no dialogue wording scored.',
      episodes: [1, 5],
      opportunity_ids: ['proto_m10_component_promise'],
      windows: [
        { id: 'm10_promise_accept', episode: 1, occasion: null },
        { id: 'm10_promise_handover', episode: 5, occasion: null },
      ],
      family_prefixes: ['proto_m10_promise_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M11',
    instrument: 'BFI-2 Conscientiousness',
    facet_or_scale: 'Responsibility',
    final_disposition: 'QUESTIONNAIRE-PRIMARY',
    disposition_class: 'questionnaire_primary',
    analysis_level:
      'Exact BFI-2 item; acknowledged seal behavior is exploratory',
    final_game_opportunity:
      'Keep the sample-seal obligation as a secondary safety/compliance observation only; do not use one narrow lapse as broad irresponsibility.',
    candidate_raw_variables: [
      'secondary_obligation_acknowledged',
      'secondary_seal_resolved_at_transfer',
    ],
    validity_gate:
      'Exact item remains in questionnaire; no hazard penalty; transfer path works; secondary telemetry labelled non-primary.',
    rival_explanations:
      'Risk interpretation; moral framing; compliance; one strong situation.',
    active_seconds: 0,
    implementation_action:
      'DOWNGRADE game task to secondary; retain exact questionnaire item.',
    episode_label: '2 — secondary only',
    primary_source: 'https://doi.org/10.1037/pspp0000096',
    route: {
      location: 'Records Workshop - sample-seal obligation (secondary only)',
      mechanic:
        'Sample-seal obligation kept as secondary safety/compliance telemetry only; no hazard penalty; never broad irresponsibility; the exact item stays in the questionnaire.',
      episodes: [2],
      opportunity_ids: [],
      windows: [],
      family_prefixes: [],
      secondary_telemetry_ids: ['secondary_m11_seal_obligation'],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M12',
    instrument: 'BFI-2 Conscientiousness',
    facet_or_scale: 'Responsibility',
    final_disposition: 'GAME-CANDIDATE — CONDITIONAL',
    disposition_class: 'conditional',
    analysis_level: 'Responsibility facet; aggregate two matched QC occasions',
    final_game_opportunity:
      'Inspect two independent completed work products, each with one visible-but-not-salient matched error, and optionally correct before submit.',
    candidate_raw_variables: [
      'error_detected_o1',
      'error_corrected_o1',
      'error_detected_o2',
      'error_corrected_o2',
      'inspection_actions',
    ],
    validity_gate:
      'Error present/reachable; inspection practiced; no time pressure; matched salience; accessibility equivalent.',
    rival_explanations:
      'Visual acuity; domain knowledge; cautiousness; interface search.',
    active_seconds: 30,
    implementation_action:
      'REVISE from one error to two matched observations; no speed score.',
    episode_label: '1 + 2',
    primary_source: 'https://doi.org/10.1037/pspp0000096',
    route: {
      location:
        'Concourse QC packet (occasion 1); Records Workshop completed work product (occasion 2)',
      mechanic:
        'Two matched, independently reachable quality-control occasions: inspect a completed work product with one visible-but-not-salient matched error and optionally correct before submit; form and order recorded; no speed score.',
      episodes: [1, 2],
      opportunity_ids: ['proto_m12_qc_o1', 'proto_m12_qc_o2'],
      windows: [
        { id: 'm12_qc_o1', episode: 1, occasion: 'o1' },
        { id: 'm12_qc_o2', episode: 2, occasion: 'o2' },
      ],
      family_prefixes: ['proto_m12_qc_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M13',
    instrument: 'BESSI-192',
    facet_or_scale: 'Information Processing Skill',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level:
      'Information Processing facet; performance method is not self-report equivalence',
    final_game_opportunity:
      'Repair a 3×3 pipe/signal network by placing and rotating a complete piece set so endpoints connect, the valve is inline and no branch remains open.',
    candidate_raw_variables: [
      'constraints_satisfied',
      'open_branch_count',
      'rotations',
      'placements',
      'valid_submission',
      'completion',
    ],
    validity_gate:
      'Worked example; complete standardized set; connectivity validator; corrections allowed; no domain-specific symbols; accessible lane.',
    rival_explanations:
      'Visuospatial ability; puzzle familiarity; motor/UI skill.',
    active_seconds: 90,
    implementation_action:
      'KEEP but fix usability: snap/rotate feedback, undo/reset, no sloppy hit targets.',
    episode_label: '2 Records & Workshop',
    primary_source: 'https://doi.org/10.1037/pspp0000401',
    route: {
      location:
        'Records Workshop - conduit lattice bench (physical 3x3 pipe network)',
      mechanic:
        'Physical 3x3 pipe/signal network: place and rotate a complete piece set so endpoints connect, the valve is inline and no branch remains open; hit targets, rotation/snap feedback, undo/reset and an accessible lane; no auto-completion, no card answer.',
      episodes: [2],
      opportunity_ids: ['proto_m13_lattice_construction'],
      windows: [{ id: 'm13_lattice_w1', episode: 2, occasion: null }],
      family_prefixes: ['proto_m13_lattice_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M14',
    instrument: 'BESSI-192',
    facet_or_scale: 'Information Processing Skill',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level:
      'Information Processing facet; capacity/work-sample component',
    final_game_opportunity:
      'One incident desk combines six messages, three gauges and one station diagram; assign faults and priorities while every source remains externally visible.',
    candidate_raw_variables: [
      'source_case_links',
      'omissions',
      'unresolved_conflicts',
      'final_assignments',
      'source_consults',
    ],
    validity_gate:
      'All sources visible; reading load controlled; no memory requirement; display accessible; independent packet/window.',
    rival_explanations:
      'Reading; interface navigation; strategy; overlap with M15 if relations are reused.',
    active_seconds: 65,
    implementation_action:
      'KEEP, but make it a spatial work surface rather than repetitive card prompts.',
    episode_label: '1 Incident Handover',
    primary_source: 'https://doi.org/10.1037/pspp0000401',
    route: {
      location: 'Concourse - multi-source incident desk (spatial work surface)',
      mechanic:
        'One incident desk combining six messages, three gauges and one station diagram; assign faults and priorities while every source remains externally visible; independent packet/window.',
      episodes: [1],
      opportunity_ids: ['proto_m14_incident_desk'],
      windows: [{ id: 'm14_desk_w1', episode: 1, occasion: null }],
      family_prefixes: ['proto_m14_desk_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M15',
    instrument: 'BESSI-192',
    facet_or_scale: 'Information Processing Skill',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level:
      'Information Processing facet; relational synthesis component',
    final_game_opportunity:
      'Build a compact causal subsystem model from independent evidence, then predict the effect of one intervention.',
    candidate_raw_variables: [
      'required_causal_edges',
      'invalid_edges',
      'corrections',
      'intervention_prediction_accuracy',
    ],
    validity_gate:
      'Independent case; diagram tutorial; domain-neutral semantics; all evidence obtainable; matched form.',
    rival_explanations: 'General reasoning; diagram literacy; reading.',
    active_seconds: 65,
    implementation_action:
      'KEEP; embed as one phase of the signal-decoder incident, not a separate room.',
    episode_label: '3 Signal Analysis',
    primary_source: 'https://doi.org/10.1037/pspp0000401',
    route: {
      location: 'Diagnostics Laboratory - signal case phase 1 (causal model)',
      mechanic:
        'Phase 1 of the signal-analysis case: build a compact causal subsystem model from independent evidence, then predict the effect of one intervention (existing relational engine and validator retained).',
      episodes: [3],
      opportunity_ids: ['proto_m15_layered_cipher'],
      windows: [{ id: 'm15_causal_w1', episode: 3, occasion: null }],
      family_prefixes: ['proto_m15_cipher_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M16',
    instrument: 'BESSI-192',
    facet_or_scale: 'Information Processing Skill',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level: 'Information Processing facet; novel-rule component',
    final_game_opportunity:
      'Learn a novel three-part alien/signal protocol and classify six unseen cases into process lanes using tokens or typed aliases.',
    candidate_raw_variables: [
      'unseen_case_accuracy',
      'rule_consistent_errors',
      'corrections',
      'study_time',
      'reference_consults',
    ],
    validity_gate:
      'Protocol genuinely novel; example comprehension; matched forms; no prior route exposure to symbols.',
    rival_explanations:
      'Reading; prior analogous knowledge; interface literacy.',
    active_seconds: 50,
    implementation_action:
      'KEEP; one concise tutorial, then unseen cases. Avoid repeated near-identical consoles.',
    episode_label: '3 Signal Analysis',
    primary_source: 'https://doi.org/10.1037/pspp0000401',
    route: {
      location: 'Diagnostics Laboratory - signal case phase 2 (novel protocol)',
      mechanic:
        'Phase 2: learn a genuinely novel three-part signal protocol and classify unseen cases into process lanes using tokens or typed aliases; one concise tutorial, then unseen cases.',
      episodes: [3],
      opportunity_ids: ['proto_m16_protocol_update'],
      windows: [{ id: 'm16_protocol_w1', episode: 3, occasion: null }],
      family_prefixes: ['proto_m16_protocol_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M17',
    instrument: 'BESSI-192',
    facet_or_scale: 'Information Processing Skill',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level: 'Information Processing facet; transfer, not speed alone',
    final_game_opportunity:
      'Observe one demonstration, complete one guided practice, then solve a changed unassisted transfer case.',
    candidate_raw_variables: [
      'practice_accuracy',
      'transfer_first_attempt',
      'transfer_correct_steps',
      'hints_used',
      'transfer_completion',
    ],
    validity_gate:
      'Novel mapping; practice criterion; changed transfer; floor/ceiling pilot; motor time not scored.',
    rival_explanations:
      'Motor sequence ability; prior analogous experience; instruction comprehension.',
    active_seconds: 55,
    implementation_action:
      'KEEP and shorten to one demo + one practice + one changed transfer.',
    episode_label: '3 Signal Analysis',
    primary_source: 'https://doi.org/10.1037/pspp0000401',
    route: {
      location:
        'Diagnostics Laboratory - signal case phase 3 (demonstration / practice / transfer)',
      mechanic:
        'Phase 3: one demonstration, one guided practice, then one changed unassisted transfer case; motor time is not scored.',
      episodes: [3],
      opportunity_ids: ['proto_m17_syntax_acquisition'],
      windows: [{ id: 'm17_transfer_w1', episode: 3, occasion: null }],
      family_prefixes: ['proto_m17_syntax_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M18',
    instrument: 'BESSI-192',
    facet_or_scale: 'Information Processing Skill',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level:
      'Information Processing facet; logical hypothesis-testing component',
    final_game_opportunity:
      'Test reversible hypotheses against independent evidence panels, eliminate contradictions and submit the sole evidence-consistent fault.',
    candidate_raw_variables: [
      'tests_selected',
      'contradictions_eliminated',
      'redundant_tests',
      'evidence_consistent_steps',
      'diagnosis_accuracy',
    ],
    validity_gate:
      'All evidence obtainable; no specialist knowledge; matched cases; independent from M13 state and events.',
    rival_explanations: 'General reasoning; search strategy; reading.',
    active_seconds: 65,
    implementation_action:
      'KEEP M18 here, not in the pipe puzzle; simplify UI and remove answer-card feel.',
    episode_label: '3 Signal Analysis',
    primary_source: 'https://doi.org/10.1037/pspp0000401',
    route: {
      location:
        'Diagnostics Laboratory - signal case phase 4 (hypothesis diagnosis)',
      mechanic:
        'Phase 4: test reversible hypotheses against independent evidence panels, eliminate contradictions and submit the sole evidence-consistent fault; independent of M13 state and events.',
      episodes: [3],
      opportunity_ids: ['proto_m18_lattice_fault_diagnosis'],
      windows: [{ id: 'm18_diagnosis_w1', episode: 3, occasion: null }],
      family_prefixes: ['proto_m18_fault_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M19',
    instrument: 'Multidimensional Persistence Scale',
    facet_or_scale: 'Persistence Despite Difficulty',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level: 'PDD scale; attainable post-difficulty behavior',
    final_game_opportunity:
      'Regulate a progressive valve/coupling task: resistance increases after initial progress, feedback stays informative and completion remains attainable.',
    candidate_raw_variables: [
      'difficulty_onset',
      'postdifficulty_reengagement',
      'useful_attempts',
      'progress',
      'completion',
      'stop_choice',
    ],
    validity_gate:
      'Difficulty understood; matched calibration; attainable endpoint; neutral stop; no zero-utility state.',
    rival_explanations:
      'Ability; attainability belief; interest; frustration tolerance.',
    active_seconds: 50,
    implementation_action:
      'KEEP as physical mechanic; pilot adaptive band before interpreting persistence.',
    episode_label: '4 Exterior Recovery',
    primary_source: 'https://doi.org/10.1016/j.paid.2018.11.005',
    route: {
      location: 'Recovery Yard - difficult valve/coupling',
      mechanic:
        'Progressive physical valve/coupling: resistance increases after initial progress, feedback stays informative, completion remains attainable, a neutral stop is always available.',
      episodes: [4],
      opportunity_ids: ['proto_m19_progressive_valve'],
      windows: [{ id: 'm19_valve_w1', episode: 4, occasion: null }],
      family_prefixes: ['proto_m19_valve_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M20',
    instrument: 'Multidimensional Persistence Scale',
    facet_or_scale: 'Persistence Despite Difficulty',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level: 'PDD scale; longitudinal return/completion component',
    final_game_opportunity:
      'Begin a multi-stage antenna restoration, leave for one required intervening duty, then receive a natural opportunity to resume and finish.',
    candidate_raw_variables: [
      'progress_pre_interruption',
      'returned',
      'resume_latency',
      'useful_resume_actions',
      'completion',
    ],
    validity_gate:
      'Task remains attainable/unchanged; guaranteed return route; identical interruption; state persists visibly.',
    rival_explanations:
      'Prospective memory; navigation; project interest; ability.',
    active_seconds: 55,
    implementation_action:
      'KEEP and use it to justify one purposeful backtrack, not maze wandering.',
    episode_label: '4 + 5',
    primary_source: 'https://doi.org/10.1016/j.paid.2018.11.005',
    route: {
      location:
        'Recovery Yard mast (start) -> Workshop Return feed console (resume/finish)',
      mechanic:
        'Multi-stage antenna restoration begun outside, interrupted by the one required return duty, then a natural (uncommanded) opportunity to resume and finish with visibly persisted state.',
      episodes: [4, 5],
      opportunity_ids: ['proto_m20_antenna_restoration'],
      windows: [
        { id: 'm20_antenna_start', episode: 4, occasion: null },
        { id: 'm20_antenna_resume', episode: 5, occasion: null },
      ],
      family_prefixes: ['proto_m20_antenna_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M21',
    instrument: 'Multidimensional Persistence Scale',
    facet_or_scale: 'Persistence Despite Difficulty',
    final_disposition: 'GAME-CANDIDATE — CONDITIONAL',
    disposition_class: 'conditional',
    analysis_level:
      'PDD scale; understanding/application required; reading time alone prohibited',
    final_game_opportunity:
      'Use a concise unfamiliar, cross-referenced manual (text + equivalent audio/diagram mode) to infer a rule and apply it to a novel repair.',
    candidate_raw_variables: [
      'reference_sections_used',
      'cross_reference_depth',
      'reengagement',
      'correct_rule_application',
      'completion',
    ],
    validity_gate:
      'Language calibrated; accessible equivalent mode; application attainable; scrolling/reading duration never primary.',
    rival_explanations:
      'Reading/language proficiency; working memory; domain familiarity.',
    active_seconds: 55,
    implementation_action:
      'REVISE for multimodal equivalence; drop if language effects dominate pilot data.',
    episode_label: '5 Return & Handover',
    primary_source: 'https://doi.org/10.1016/j.paid.2018.11.005',
    route: {
      location: 'Workshop Return - manual-based repair',
      mechanic:
        'Concise unfamiliar cross-referenced manual (text + equivalent diagram mode) used to infer a rule and apply it to a novel repair; reading duration is never primary.',
      episodes: [5],
      opportunity_ids: ['proto_m21_manual_repair'],
      windows: [{ id: 'm21_manual_w1', episode: 5, occasion: null }],
      family_prefixes: ['proto_m21_manual_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M22',
    instrument: 'Multidimensional Persistence Scale',
    facet_or_scale: 'Persistence Despite Difficulty',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level: 'PDD scale; standardized setback/recovery component',
    final_game_opportunity:
      'Submit a reasonable report, receive a standardized newly revealed criterion, then revise and resubmit using actionable feedback.',
    candidate_raw_variables: [
      'setback_presented',
      'revision_started',
      'feedback_consistent_edits',
      'resubmitted',
      'recovery_complete',
    ],
    validity_gate:
      'Initial response valid; feedback understood; recovery attainable; no blame framing; same criterion by form.',
    rival_explanations: 'Writing; attribution; feedback comprehension.',
    active_seconds: 50,
    implementation_action:
      'KEEP; use direct editing/assembly rather than four multiple-choice report cards.',
    episode_label: '5 Return & Handover',
    primary_source: 'https://doi.org/10.1016/j.paid.2018.11.005',
    route: {
      location: 'Workshop Return - shift report desk',
      mechanic:
        'Submit a reasonable assembled report, receive a standardised newly revealed criterion, then revise and resubmit using actionable feedback (direct editing/assembly, not multiple-choice cards).',
      episodes: [5],
      opportunity_ids: ['proto_m22_report_revision'],
      windows: [{ id: 'm22_report_w1', episode: 5, occasion: null }],
      family_prefixes: ['proto_m22_report_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M23',
    instrument: 'Multidimensional Persistence Scale',
    facet_or_scale: 'Persistence Despite Difficulty',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level: 'PDD scale; useful adaptive retries only',
    final_game_opportunity:
      'Scanner-guided excavation: use C-strength/bearing feedback to narrow a bounded field, then D-dig exact terrain cells to recover an attainable buried component.',
    candidate_raw_variables: [
      'informative_scan_moves',
      'signal_strength_changes',
      'exact_dig_attempts',
      'useful_strategy_shifts',
      'recovery_complete',
    ],
    validity_gate:
      'Scanner tutorial passed; target fixed/counterbalanced; feedback truthful; task attainable; blind/random actions excluded; no M24 events.',
    rival_explanations:
      'Spatial reasoning; navigation; control familiarity; search strategy.',
    active_seconds: 60,
    implementation_action:
      'PREFER current scan/dig mechanics over another pseudo-command console; keep item-local bounded field.',
    episode_label: '4 Exterior Recovery',
    primary_source: 'https://doi.org/10.1016/j.paid.2018.11.005',
    route: {
      location: 'Recovery Yard - scanner-guided excavation plot',
      mechanic:
        'Existing scanner-guided excavation: C-strength/bearing feedback narrows a bounded field, D-dig exact terrain cells to recover an attainable buried component; bounded and recoverable; useful progress distinguished from aimless time.',
      episodes: [4],
      opportunity_ids: ['proto_m23_field_recovery'],
      windows: [{ id: 'm23_excavation_w1', episode: 4, occasion: null }],
      family_prefixes: ['proto_m23_field_recovery_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M24',
    instrument: 'Multidimensional Persistence Scale',
    facet_or_scale: 'Inappropriate Persistence',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level: 'IP scale; behavior only after verified zero utility',
    final_game_opportunity:
      'Metal Recovery Yard magnet rig: complete a finite useful deck; then show and acknowledge objective depletion while an equally visible useful alternative is available.',
    candidate_raw_variables: [
      'depletion_reached',
      'depletion_acknowledged',
      'postdepletion_casts',
      'identical_postdepletion_cycles',
      'alternative_opened',
    ],
    validity_gate:
      'Finite deck advances consistently; zero utility objectively true; no random jackpot after depletion; comprehension confirmed; misses before depletion excluded.',
    rival_explanations:
      'Signal trust; curiosity; learned reward history; timing-game skill.',
    active_seconds: 55,
    implementation_action:
      'KEEP magnet fishing; make deck/depletion state unambiguous and persist across room returns.',
    episode_label: '4 Exterior Recovery',
    primary_source: 'https://doi.org/10.1016/j.paid.2018.11.005',
    route: {
      location: 'Metal Recovery Yard - magnet rig (F, rig-local)',
      mechanic:
        'Finite magnet-recovery deck; every completed cycle advances the deck; objective depletion shown and acknowledged with an equally visible useful alternative; state persists across room returns; no reward after depletion; misses, empty pulls and depletion remain distinguishable.',
      episodes: [4],
      opportunity_ids: ['proto_m24_magnet_utility'],
      windows: [{ id: 'm24_magnet_w1', episode: 4, occasion: null }],
      family_prefixes: ['proto_m24_magnet_utility_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M25',
    instrument: 'Multidimensional Persistence Scale',
    facet_or_scale: 'Inappropriate Persistence',
    final_disposition: 'QUESTIONNAIRE-PRIMARY / HYBRID REQUIRED',
    disposition_class: 'questionnaire_primary',
    analysis_level: 'Private belief cannot be inferred from repetition',
    final_game_opportunity:
      'A locked-command repetition task may remain exploratory, but interpretation requires the exact questionnaire item or a transparent direct belief/expectancy probe.',
    candidate_raw_variables: [
      'secondary_unchanged_resubmits_after_lock',
      'direct_belief_probe',
      'lock_comprehension',
    ],
    validity_gate:
      'No game-only score; lock understood; bounce suppressed; reset visible; direct belief measure stored separately.',
    rival_explanations:
      "Habit; interface error; curiosity; the source item's belief clause is unobserved behaviorally.",
    active_seconds: 0,
    implementation_action:
      'REMOVE primary game-only inference; retain exact questionnaire item and optional hybrid research probe.',
    episode_label: '5 — questionnaire/hybrid',
    primary_source: 'https://doi.org/10.1016/j.paid.2018.11.005',
    route: {
      location:
        'Workshop Return - transparent self-report probe (questionnaire/hybrid)',
      mechanic:
        'Transparent direct belief/expectancy probe presented openly as a self-report item and stored separately from every behavioural component; the exact source item remains in the questionnaire; any locked-command repetition telemetry is secondary context only.',
      episodes: [5],
      opportunity_ids: ['proto_m25_belief_probe'],
      windows: [{ id: 'm25_probe_w1', episode: 5, occasion: null }],
      family_prefixes: ['proto_m25_probe_'],
      secondary_telemetry_ids: ['secondary_m25_lock_resubmits'],
      implementation_status: 'planned',
    },
  },
  {
    id: 'M26',
    instrument: 'Multidimensional Persistence Scale',
    facet_or_scale: 'Inappropriate Persistence',
    final_disposition: 'GAME-CANDIDATE — STRONG',
    disposition_class: 'strong',
    analysis_level: 'IP scale; post-knowledge behavior only',
    final_game_opportunity:
      'After one successful transmission, physically disconnect the channel, demonstrate and acknowledge the state, while a working alternative channel remains available.',
    candidate_raw_variables: [
      'disconnect_acknowledged',
      'confirmation_probe_excluded',
      'postknowledge_transmissions',
      'alternative_used',
    ],
    validity_gate:
      'Worthlessness beyond doubt; first confirmation probe excluded; alternative equally accessible; no hidden recovery.',
    rival_explanations: 'Signal trust; curiosity; desire to test once.',
    active_seconds: 40,
    implementation_action:
      'KEEP with explicit knowledge check and persistent physical disconnect state.',
    episode_label: '4 Exterior Recovery',
    primary_source: 'https://doi.org/10.1016/j.paid.2018.11.005',
    route: {
      location: 'Recovery Yard - transmission channel post',
      mechanic:
        'After one successful transmission the channel is physically disconnected, demonstrated and acknowledged while a working alternative channel remains equally available; the first confirmation probe is excluded; the disconnect state persists.',
      episodes: [4],
      opportunity_ids: ['proto_m26_channel_disconnect'],
      windows: [{ id: 'm26_channel_w1', episode: 4, occasion: null }],
      family_prefixes: ['proto_m26_channel_'],
      secondary_telemetry_ids: [],
      implementation_status: 'planned',
    },
  },
];

export function ledgerEntry(id: LedgerItemId): EvidenceLedgerEntry {
  const entry = EVIDENCE_LEDGER.find((candidate) => candidate.id === id);

  if (entry === undefined) {
    throw new Error(`Unknown ledger item: ${id}`);
  }

  return entry;
}

export function ledgerClassificationCounts(): Record<
  LedgerDispositionClass,
  number
> {
  const counts: Record<LedgerDispositionClass, number> = {
    strong: 0,
    conditional: 0,
    questionnaire_primary: 0,
  };

  for (const entry of EVIDENCE_LEDGER) {
    counts[entry.disposition_class] += 1;
  }

  return counts;
}

/** Every primary family prefix across the ledger (pairwise-disjointness tests). */
export function ledgerFamilyPrefixes(): readonly string[] {
  return EVIDENCE_LEDGER.flatMap((entry) => entry.route.family_prefixes);
}

/** Every provisional opportunity id across the ledger. */
export function ledgerOpportunityIds(): readonly string[] {
  return EVIDENCE_LEDGER.flatMap((entry) => entry.route.opportunity_ids);
}

/** Ledger entries hosting a window in the given episode. */
export function ledgerItemsInEpisode(
  episode: LedgerEpisode,
): readonly EvidenceLedgerEntry[] {
  return EVIDENCE_LEDGER.filter((entry) =>
    entry.route.windows.some((window) => window.episode === episode),
  );
}
